leftnav:
- identifier: 6655ed60-8b47-9590-c188-ac38e60c8148
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 5f2fc942-3ed8-0f75-e98d-30fb639ca44f
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 010c6dcf-1d6f-aefc-1d7c-a1c6b989f19d
  name: Assignments
  pageRef: /pages/assignments
  weight: 30
